platform :ios, '7.0'
pod 'TTTAttributedLabel'
pod 'AFNetworking', '~> 2.2.0'
pod 'Reveal-iOS-SDK', '~> 1.0.4'
pod 'SDWebImage', '~> 3.6'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.0.5'
pod 'AVHexColor', '~> 1.2.0'
pod 'Mantle', '~> 1.5'
pod 'DateTools', '~> 1.3.0'
